title: Pedro Figueiroa
baseURL: https://cvpedrofigueiroa.netlify.app/
theme: hugo-resume
languageCode: en-us
PygmentsCodeFences: yes
PygmentsCodeFencesGuessSyntax: yes
PygmentsStyle: monokai
enableGitInfo: no
params:
  address: Belo Horizonte, MG
  email: pedroiki03@gmail.com
  favicon: /favicon.ico
  firstName: Pedro
  google:
    analytics:
      trackerID: XX-123446-01
  handles:
    - link: https://www.linkedin.com/in/pedro-henrique-cea-211414211/
      name: LinkedIn
    - link: https://github.com/eddiewebb/
      name: GitHub
    - link: https://bitbucket.org/eddiewebb/
      name: Bitbucket
    - link: https://stackoverflow.com/users/story/82880
      name: Stack Overflow
    - link: https://keybase.io/edwardawebb
      name: Keybase
  lastName: Webb
  phone: +55(31)98737-7372
  profileImage: img/TechChat.png
  showEducation: yes
  showExperience: yes
  showOpenSource: yes
  showProjects: yes
  showPublications: yes
  showQr: yes
  showSkills: yes
outputs:
  home:
    - HTML
    - JSON
taxonomies:
  tag: tags
